#pragma once

namespace twsim::app {

enum class PageId {
  HomeRingHost,
  Watchface,
  Launcher,
  Notifications,
  NotificationWakePreview,
  QuickSettings,
  PowerMenu,
  ScreenOff,
  PoweredOff,
  LongBatteryWatchface,
  LongBatteryExit,
  HomeShortcutPayments,
  HomeShortcutNfc,
  HomeShortcutHealth,
  HomeShortcutWeather,
  Gps,
  Recorder,
  AudioPlayer,
  VideoPlayer,
  Infrared,
  Pedometer,
  PedometerDataInfo,
  Lora,
  SettingsHome,
  SettingDisplay,
  SettingDisplayBrightness,
  SettingDisplayManualBrightness,
  SettingDisplayTimeout,
  SettingDisplayRaiseToWake,
  SettingDisplayRaiseToWakeStartTime,
  SettingDisplayRaiseToWakeEndTime,
  SettingDisplayKeepScreenOn,
  SettingDisplayScreenOffDisplay,
  SettingDisplayScreenOffDisplaySchedule,
  SettingDisplayScreenOffDisplayStartTime,
  SettingDisplayScreenOffDisplayEndTime,
  SettingDisplayScreenOffStyle,
  SettingSound,
  SettingDoNotDisturb,
  SettingNotifications,
  SettingAppLayout,
  SettingSystemActions,
  SettingAbout,
  SettingTimeDate,
  SettingBattery,
  SettingBatteryLifeMode,
  SettingBatteryOptimization,
  SettingBatteryInfo,
  SettingBluetooth,
  SettingWifi,
  SettingDeveloper,
  SettingVersion,
  AppHeartRate,
  AppBloodOxygen,
  AppBreathing,
  AppStress,
  AppSleep,
  AppWeather,
  AppNfc,
  AppAlipay,
  AppWeChatPay,
  TimingToolsHome,
  Stopwatch,
  Timer,
  Alarm,
  GamesHome,
  Game2048,
  Calculator,
};

const char* page_name(PageId page_id);

}  // namespace twsim::app
