#include "App/UI/PageId.h"

namespace twsim::app {

const char* page_name(PageId page_id) {
  switch (page_id) {
    case PageId::HomeRingHost:
      return "HomeRingHost";
    case PageId::Watchface:
      return "Watchface";
    case PageId::Launcher:
      return "Launcher";
    case PageId::Notifications:
      return "Notifications";
    case PageId::NotificationWakePreview:
      return "NotificationWakePreview";
    case PageId::QuickSettings:
      return "QuickSettings";
    case PageId::PowerMenu:
      return "PowerMenu";
    case PageId::ScreenOff:
      return "ScreenOff";
    case PageId::PoweredOff:
      return "PoweredOff";
    case PageId::LongBatteryWatchface:
      return "LongBatteryWatchface";
    case PageId::LongBatteryExit:
      return "LongBatteryExit";
    case PageId::HomeShortcutPayments:
      return "HomeShortcutPayments";
    case PageId::HomeShortcutNfc:
      return "HomeShortcutNfc";
    case PageId::HomeShortcutHealth:
      return "HomeShortcutHealth";
    case PageId::HomeShortcutWeather:
      return "HomeShortcutWeather";
    case PageId::Gps:
      return "Gps";
    case PageId::Recorder:
      return "Recorder";
    case PageId::AudioPlayer:
      return "AudioPlayer";
    case PageId::VideoPlayer:
      return "VideoPlayer";
    case PageId::Infrared:
      return "Infrared";
    case PageId::Pedometer:
      return "Pedometer";
    case PageId::PedometerDataInfo:
      return "PedometerDataInfo";
    case PageId::Lora:
      return "Lora";
    case PageId::SettingsHome:
      return "SettingsHome";
    case PageId::SettingDisplay:
      return "SettingDisplay";
    case PageId::SettingDisplayBrightness:
      return "SettingDisplayBrightness";
    case PageId::SettingDisplayManualBrightness:
      return "SettingDisplayManualBrightness";
    case PageId::SettingDisplayTimeout:
      return "SettingDisplayTimeout";
    case PageId::SettingDisplayRaiseToWake:
      return "SettingDisplayRaiseToWake";
    case PageId::SettingDisplayRaiseToWakeStartTime:
      return "SettingDisplayRaiseToWakeStartTime";
    case PageId::SettingDisplayRaiseToWakeEndTime:
      return "SettingDisplayRaiseToWakeEndTime";
    case PageId::SettingDisplayKeepScreenOn:
      return "SettingDisplayKeepScreenOn";
    case PageId::SettingDisplayScreenOffDisplay:
      return "SettingDisplayScreenOffDisplay";
    case PageId::SettingDisplayScreenOffDisplaySchedule:
      return "SettingDisplayScreenOffDisplaySchedule";
    case PageId::SettingDisplayScreenOffDisplayStartTime:
      return "SettingDisplayScreenOffDisplayStartTime";
    case PageId::SettingDisplayScreenOffDisplayEndTime:
      return "SettingDisplayScreenOffDisplayEndTime";
    case PageId::SettingDisplayScreenOffStyle:
      return "SettingDisplayScreenOffStyle";
    case PageId::SettingSound:
      return "SettingSound";
    case PageId::SettingDoNotDisturb:
      return "SettingDoNotDisturb";
    case PageId::SettingNotifications:
      return "SettingNotifications";
    case PageId::SettingAppLayout:
      return "SettingAppLayout";
    case PageId::SettingSystemActions:
      return "SettingSystemActions";
    case PageId::SettingAbout:
      return "SettingAbout";
    case PageId::SettingTimeDate:
      return "SettingTimeDate";
    case PageId::SettingBattery:
      return "SettingBattery";
    case PageId::SettingBatteryLifeMode:
      return "SettingBatteryLifeMode";
    case PageId::SettingBatteryOptimization:
      return "SettingBatteryOptimization";
    case PageId::SettingBatteryInfo:
      return "SettingBatteryInfo";
    case PageId::SettingBluetooth:
      return "SettingBluetooth";
    case PageId::SettingWifi:
      return "SettingWifi";
    case PageId::SettingDeveloper:
      return "SettingDeveloper";
    case PageId::SettingVersion:
      return "SettingVersion";
    case PageId::AppHeartRate:
      return "AppHeartRate";
    case PageId::AppBloodOxygen:
      return "AppBloodOxygen";
    case PageId::AppBreathing:
      return "AppBreathing";
    case PageId::AppStress:
      return "AppStress";
    case PageId::AppSleep:
      return "AppSleep";
    case PageId::AppWeather:
      return "AppWeather";
    case PageId::AppNfc:
      return "AppNfc";
    case PageId::AppAlipay:
      return "AppAlipay";
    case PageId::AppWeChatPay:
      return "AppWeChatPay";
    case PageId::TimingToolsHome:
      return "TimingToolsHome";
    case PageId::Stopwatch:
      return "Stopwatch";
    case PageId::Timer:
      return "Timer";
    case PageId::Alarm:
      return "Alarm";
    case PageId::GamesHome:
      return "GamesHome";
    case PageId::Game2048:
      return "Game2048";
    case PageId::Calculator:
      return "Calculator";
    default:
      return "Unknown";
  }
}

}  // namespace twsim::app
