#pragma once

namespace twsim::app {

enum class PageId {
  Watchface,
  Launcher,
  Notifications,
  NotificationWakePreview,
  QuickSettings,
  PowerMenu,
  ScreenOff,
  PoweredOff,
  HomeShortcutPayments,
  HomeShortcutNfc,
  HomeShortcutHealth,
  HomeShortcutWeather,
  Gps,
  Recorder,
  AudioPlayer,
  VideoPlayer,
  Infrared,
  Pedometer,
  Lora,
  SettingsHome,
  SettingDisplay,
  SettingAppLayout,
  SettingTimeDate,
  SettingSound,
  SettingBattery,
  SettingBluetooth,
  SettingWifi,
  SettingDeveloper,
  SettingVersion,
  AppHeartRate,
  AppBloodOxygen,
  AppBreathing,
  AppStress,
  AppSleep,
  AppWeather,
  AppNfc,
  AppAlipay,
  AppWeChatPay,
  TimingToolsHome,
  Stopwatch,
  Timer,
  Alarm,
  GamesHome,
  Game2048,
  Calculator,
};

const char* page_name(PageId page_id);

}  // namespace twsim::app
